#!/usr/bin/env python3
from src import cli

if __name__ == '__main__':
    try:
        cli.run()  # Main CLI entry point
    except KeyboardInterrupt as e:
        print("exiting...")
        exit(1)
